# Site
repository: RomainBoquet/romainboquet.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Romain Boquet
title: Data Scientist
email: romain.boquett@gmail.com
website: www.github.com/RomainBoquet

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: RomainBoquet
linkedin_username: romain-boquet

# About Section
# about_title: About Me
about_profile_image: images/img.jpg
about_content: |
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Mes projets
    layout: list
    content:
      - layout: top-middle
        title: Snake RL (2025)
        link: github.com/RomainBoquet/snake-RL
        description: |
          description

      - layout: top-middle
        title: Computer vision pour les voitures autonomes
        link: github.com/RomainBoquet/snake-RL
        description: |
          Ce projet a pour but de faire de la segmentation d'images sur le dataset Cityscapes.
          
          L'objectif est d'entraîner le modèle Bisenet, pour faire de la segmentation d'images en temps réel.


      - layout: top-middle
        title: Emotion Island (2022-2024)
        description: |
          Lancé par une sophrologue, j'ai pu particier à ce projet regroupant 12 étudiants.

          L'objectif était de créer un jeu vidéo pour aider les enfants dans la gestion de leurs émotions.
          
          ![Emotion Island](images/emotion-island.jpg){: .project-image }


  - title: Experience
    layout: list
    content:
      - layout: left
        title: Sanofi
        link: link.com
        sub_title: Alternant Data Scientist
        caption: Septembre 2024 - Actuellement
        quote: >
          Poursuivre les miracles de la science pour améliorer la vie des gens.
        description: |
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: Formation
    layout: list
    content:
      - layout: left
        title: École Centrale de Lille
        caption: 2022 - 2025
        sub_title: Diplôme d'ingénieur généraliste
        description: |
          - Semestre en Erasmus à Turin : Spécialisation en Data et en Machine learning
          - Certification en gestion de projet : MOOC GDP 20
     
      - layout: left
        title: Lycée Pierre Corneille (Rouen)
        caption: 2020 - 2022
        sub_title: Classe préparatoire MPSI / PSI*
        description: |
          - Projet de robotique et informatique : Création d'un fauteuil roulant omnidirectionnel
          
      - layout: left
        title: Lycée Jean XXIII (Yvetot)
        caption: 2017 - 2020
        sub_title: Baccalauréat scientifique mention très bien

  - title: Un peu plus sur moi
    layout: text
    content: |
      Au delà de mon intêret pour la data science, j'ai aussi d'autres passions :
      - Escalade
      - Badminton
      - Cinéma

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
